export const routeToActiveMap: Record<string, string> = {
    '/': 'home',
    '/about-us': 'Company',
    '/awards-certificates': 'Company',
    '/blogs': 'Company',
    '/all-assets': 'Assets',
    '/glass-fitting-assets': 'Assets',
    '/smart-locks-assets': 'Assets',
    '/safes-assets': 'Assets',
    '/shower-assets': 'Assets',
    '/kitchen-furniture-assets': 'Assets',
    '/catalogues': 'Catalogues',
    '/collections': 'Collections',
    '/all-brands': 'Brands',
    '/ozone-india-brands': 'Brands',
    '/godrej-india-brands': 'Brands',
    '/brands/:slugs': 'Brands',
    '/neo-brands': 'Brands',
    '/ironwood-brands': 'Brands',
    '/ozoneindia': 'Contact',
    '/contactus': 'Contact',
    '/neo': 'Contact',
    '/godrejindia': 'Contact',
    '/ironwood': 'Contact',

};